name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install --settings ~/creds/settings.xml

      - name: Deploy with Maven
        if: github.event_name == 'release' && github.event.action == 'published'
        run: mvn deploy -P release --settings ~/creds/settings.xml

