name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: |
            ~/jdk
          key: ${{ runner.os }}-jdk-21

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          java-package: jdk
          cache: 'custom'
          cache-directory: '~/jdk'

      - name: Build with Maven
        run: mvn clean install
